
AlgorithmSelection()
getpoddistances()
demand_redistribution()
reset_route()
dedicated_vehicle()
partitionRoute()
removePodByIdOnlyFromListOfPods()
podListContainPodWithId()
routeWithLowestTime()
routeWithLowestCapacity()
addInRssLocation()
findClosestRssPointToPod()
getMaxCapacityRouteIndex()
getMaxTimeRouteIndex()
isallRoutesUnderAllowedTime()
isallRoutesUnderAllowedCapacity()
printPodDiffsFromLists()

selectRouteFromConstraintsToAddPod()
isRoutesUnderConstraints()
selectRouteIndexToOptimize()
setupRoutesForSecondPhase()